# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('stream_updated', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('favourites_only', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='wall.Event')),
            ],
            options={
                'verbose_name_plural': 'searches',
            },
        ),
        migrations.CreateModel(
            name='StreamItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('provider', models.CharField(max_length=255)),
                ('remote_id', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=b'events/stream/items')),
                ('url', models.URLField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='wall.Event')),
            ],
            options={
                'ordering': ('-date',),
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='StreamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('remote_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=b'events/stream/avatars')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='streamuser',
            unique_together=set([('provider', 'remote_id')]),
        ),
        migrations.AddField(
            model_name='streamitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wall.StreamUser'),
        ),
        migrations.AlterUniqueTogether(
            name='streamitem',
            unique_together=set([('provider', 'remote_id')]),
        ),
    ]
