# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stream_background',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'events/stream'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
