# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20160223_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stream_updating',
            field=models.BooleanField(default=False),
        ),
    ]
